Messenger/Messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main.views import MainView
from settings_app.views import UserUpdateView
from chat_app.views import ChatsView
from settings_app.views import save_username
from post_app.views import show_post

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authorization/', include("user_app.urls")),
    path('', MainView.as_view(), name= "main"),
    path("friends/", include("friends.urls")),
    path("publications/", include("post_app.urls")),
    path("settings/<int:pk>/", UserUpdateView.as_view(), name="settings"),
    path("settings/", include("settings_app.urls")),
    path("", include("main.urls")),
    path("chats/", ChatsView.as_view(), name= "chats"),
    path("chats/", include("chat_app.urls")),
    path("save_username/<str:username>/", save_username, name= "save_username"),
    path("show_post/<int:post_pk>/", show_post, name = "show_post")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Messenger/friends/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', FriendsView.as_view(), name='friends'),
    path('requests', RequestsView.as_view(), name='requests'),
    path('recomendations', RecomendationsView.as_view(), name='recomendations'),
    path('allfriends', AllFriendsView.as_view(), name='all_friends'),
    path('request_friend/<int:pk>', request_friend, name='request_friend'),
    path('accept_friend/<int:pk>', accept_friend, name='accept_friend'),
    # path('reject_friend/<int:pk>', reject_friend, name='reject_friend'),
    path('delete_friend/<int:pk>', delete_friend, name='delete_friend'),
    path('friend_view/<int:friend_pk>', FriendView.as_view(), name='friend_view')
]

Messenger/main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("add_info", create_name_surname, name = "add_info"),
    path("get_user_readers", get_user_readers, name = "get_user_readers"),
    path("get_user_photo", get_user_photo, name = "get_user_photo"),
    path("get_user_groups", get_user_photo, name = "get_user_groups"),
    path('get_user_requests', get_user_requests, name = "get_user_requests")
]

Messenger/friends/models.py
from django.db import models

# Create your models here.

Messenger/post_app/models.py
from django.db import models
from django.contrib.auth.models import User
from user_app.models import Profile

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField(max_length=4096)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    images = models.ManyToManyField('Image', blank=True, related_name='posts_authored')
    views = models.ManyToManyField(Profile, blank=True, related_name='posts_viewed')
    likes = models.ManyToManyField(Profile, blank=True, related_name='posts_liked')
    tags = models.ManyToManyField('Tag', blank=True)
    topic = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Image(models.Model):
    filename = models.CharField(max_length=150)
    file = models.ImageField(upload_to='images/posts')
    uploaded_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.filename
    

class Album(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    preview_image = models.ImageField(upload_to='images/album_previews', null=True, blank=True)
    images = models.ManyToManyField(Image, blank=True)
    shown = models.BooleanField(default=True) # Чи відображається цей альбом
    topic = models.ForeignKey('Tag', on_delete=models.CASCADE)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
    

class Link(models.Model):
    url = models.URLField(max_length=200)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'Посилання для поста "{self.post}"'

Messenger/user_app/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
import random

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField()
    signature = models.ImageField(upload_to='images/signatures', blank=True, null=True)

    def __str__(self):
        return self.user.username
    

class Avatar(models.Model):
    image = models.ImageField(upload_to='images/avatars')
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    active = models.BooleanField(default=True) # Чи активна ця аватарка (чи використовується вона у профілі)
    shown = models.BooleanField(default=True) # Чи показана ця аватарка в альбомі минулих аватарок

    def __str__(self):
        return f'Аватар для профілю {self.profile}'

        
class Friendship(models.Model):
    profile1 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='friendship_sent_request') # Той, хто надіслав запит на дружбу
    profile2 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='friendship_accepted_request') # Той, хто має прийняти запит на дружбу
    accepted = models.BooleanField(default=False) # Чи прийнято запит на дружбу

    def __str__(self):
        return f'Дружба між {self.profile1} та {self.profile2}'
    

class VerificationCode(models.Model):
    username = models.CharField(max_length=150)
    code = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    
    @classmethod
    def generate_code(cls):
        return ''.join([str(random.randint(0, 9)) for i in range(6)])
    
    def is_valid(self):
        expiration_time = timezone.timedelta(minutes=30)
        return timezone.now() < self.created_at + expiration_time
    


Messenger/friends/views.py
from django.views.generic import TemplateView
from user_app.models import Profile, Friendship
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, JsonResponse
from post_app.models import Post
from django.shortcuts import redirect

class FriendsView(TemplateView):
    template_name = "friends.html"


    def post(self, request, *args, **kwargs):
        if request.POST.get("delete"):
            button = request.POST.get("delete")

        return HttpResponseRedirect('/friends/')
    
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        
        all_accepted = []

        user = self.request.user
        
        all_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = user), accepted = True)
        all_accepted_sent_requests = Friendship.objects.filter(profile1 = Profile.objects.get(user = user), accepted = True)
        for request in all_accepted_get_requests:
            all_accepted.append(request)
        for request in all_accepted_sent_requests:
            all_accepted.append(request)

        context["friends"] = all_accepted

        all_not_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = user), accepted = False)

        context["requests"] = all_not_accepted_get_requests

        recomended = Profile.objects.all()

        final_recomended = []

        for profile in recomended:
            print(profile.id)
            print(Friendship.objects.filter(profile1 = Profile.objects.get(user = user)).values_list("profile2"))
            if profile != Profile.objects.get(user = user) and (profile.id,) not in Friendship.objects.filter(profile2 = Profile.objects.get(user = user)).values_list("profile1") and (profile.id,) not in Friendship.objects.filter(profile1 = Profile.objects.get(user = user)).values_list("profile2") and (profile.id,) not in all_not_accepted_get_requests.values_list("profile1"):
                final_recomended.append(profile)

        context['recomended_friends'] = final_recomended

        return context
    
    def dispatch(self, request, *args, **kwargs):
        try:
            if not request.user.is_authenticated:
                return redirect("register")
        except:
            return redirect("register")
        return super().dispatch(request, *args, **kwargs)

    
class RequestsView(TemplateView):
    template_name = "requests.html"

    def post(self, request, *args, **kwargs):
        if request.POST.get("accept"):
            button = request.POST.get("accept")
            
            user = User.objects.get(id = button)
            profile_now = Profile.objects.get(user_id = request.user.pk)
            all_friends = list(profile_now.friends.all())
            all_friends.append(user)
            profile_now.friends.set(all_friends)
            profile_now.save()

            all_requests = list(profile_now.requests.all())
            all_requests.remove(user)
            profile_now.requests.set(all_requests)
            profile_now.save()

        elif request.POST.get("decline"):
            button = request.POST.get("decline")

            user = User.objects.get(id = button)
            profile_now = Profile.objects.get(user_id = request.user.pk)
            all_requests = list(profile_now.requests.all())
            all_requests.remove(user)
            profile_now.requests.set(all_requests)
            profile_now.save()

        return HttpResponseRedirect('/requests/')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        all_accepted = []

        user = self.request.user
        
        all_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = user), accepted = True)
        all_accepted_sent_requests = Friendship.objects.filter(profile1 = Profile.objects.get(user = user), accepted = True)
        for request in all_accepted_get_requests:
            all_accepted.append(request)
        for request in all_accepted_sent_requests:
            all_accepted.append(request)

        context["friends"] = all_accepted

        all_not_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = user), accepted = False)

        context["requests"] = all_not_accepted_get_requests

        recomended = Profile.objects.all()

        final_recomended = []

        for profile in recomended:
            print(profile.id)
            print(Friendship.objects.filter(profile1 = Profile.objects.get(user = user)).values_list("profile2"))
            if profile != Profile.objects.get(user = user) and (profile.id,) not in Friendship.objects.filter(profile2 = Profile.objects.get(user = user)).values_list("profile1") and (profile.id,) not in Friendship.objects.filter(profile1 = Profile.objects.get(user = user)).values_list("profile2") and (profile.id,) not in all_not_accepted_get_requests.values_list("profile1"):
                final_recomended.append(profile)

        context['recomended_friends'] = final_recomended

        return context

class RecomendationsView(TemplateView):
    template_name = "recomendations.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        all_accepted = []

        user = self.request.user
        
        all_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = user), accepted = True)
        all_accepted_sent_requests = Friendship.objects.filter(profile1 = Profile.objects.get(user = user), accepted = True)
        for request in all_accepted_get_requests:
            all_accepted.append(request)
        for request in all_accepted_sent_requests:
            all_accepted.append(request)

        context["friends"] = all_accepted

        all_not_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = user), accepted = False)

        context["requests"] = all_not_accepted_get_requests

        recomended = Profile.objects.all()

        final_recomended = []

        for profile in recomended:
            print(profile.id)
            print(Friendship.objects.filter(profile1 = Profile.objects.get(user = user)).values_list("profile2"))
            if profile != Profile.objects.get(user = user) and (profile.id,) not in Friendship.objects.filter(profile2 = Profile.objects.get(user = user)).values_list("profile1") and (profile.id,) not in Friendship.objects.filter(profile1 = Profile.objects.get(user = user)).values_list("profile2") and (profile.id,) not in all_not_accepted_get_requests.values_list("profile1"):
                final_recomended.append(profile)

        context['recomended_friends'] = final_recomended

        return context

        return context
    
class AllFriendsView(TemplateView):
    template_name = "all_friends.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        all_accepted = []

        user = self.request.user
        
        all_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = user), accepted = True)
        all_accepted_sent_requests = Friendship.objects.filter(profile1 = Profile.objects.get(user = user), accepted = True)
        for request in all_accepted_get_requests:
            all_accepted.append(request)
        for request in all_accepted_sent_requests:
            all_accepted.append(request)

        context["friends"] = all_accepted

        all_not_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = user), accepted = False)

        context["requests"] = all_not_accepted_get_requests

        recomended = Profile.objects.all()

        final_recomended = []

        for profile in recomended:
            print(profile.id)
            print(Friendship.objects.filter(profile1 = Profile.objects.get(user = user)).values_list("profile2"))
            if profile != Profile.objects.get(user = user) and (profile.id,) not in Friendship.objects.filter(profile2 = Profile.objects.get(user = user)).values_list("profile1") and (profile.id,) not in Friendship.objects.filter(profile1 = Profile.objects.get(user = user)).values_list("profile2") and (profile.id,) not in all_not_accepted_get_requests.values_list("profile1"):
                final_recomended.append(profile)

        context['recomended_friends'] = final_recomended

        return context
    
def request_friend(request, pk):
    if Friendship.objects.get_or_create(profile1 = Profile.objects.get(user = request.user), profile2 = Profile.objects.get(id = pk)) == None and Friendship.objects.get_or_create(profile1 =Profile.objects.get(user= User.objects.get(id = pk)), profile2 =  Profile.objects.get(user = request.user)) == None:
        new_friendship = Friendship.objects.create(profile1 = Profile.objects.get(user = request.user), profile2 = Profile.objects.get(id = pk))
        new_friendship.save()

    return JsonResponse({"status": "ok"})

def accept_friend(request, pk):
    print(request.POST.get("friendship_id"))
    accept_friendship = Friendship.objects.get(id = int(request.POST.get("friendship_id")))
    accept_friendship.accepted = True
    accept_friendship.save()

    return JsonResponse({"status": "ok"})
    # user = User.objects.get(id = pk)
    # profile_now = Profile.objects.get(user_id = request.user.pk)
    # profile_user = Profile.objects.get(user_id = user.pk)
    # all_friends = list(profile_now.friends.all())
    # all_friends.append(user)
    # profile_now.friends.set(all_friends)
    # profile_now.save()

    # all_requests = list(request.user.requests.all())

Messenger/friends/templates/all_friends.html
{% extends "base.html" %}
{% load static %}


{% block title %} Friend Requests {% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'styles/friends.css' %}">
<script src="{% static 'js/jquery-3.7.1.min.js' %}" defer></script>
<script src="{% static 'js/friends.js' %}" defer></script>
{% endblock %}

{% block content %}
<header>
    <img src="{% static 'images/logo.png' %}" class="logo">
    <div class="tabsExit">
        <div class="tabs">
            <a href="{% url 'main' %}" class="main tab"><img src="{% static 'images/main.png' %}">Головна</a>

            <a href="{% url 'my_publications' %}" class="publications tab"><img
                    src="{% static 'images/publications.png' %}">Мої публікації</a>

            <a href="{% url 'friends' %}" class="friends tab tab-now"><img
                    src="{% static 'images/friends.png' %}">Друзі</a>

            <a href="{% url 'chats' %}" class="chats tab"><img src="{% static 'images/chat.png' %}">Чати</a>

            <a href="{% url 'settings' user.pk %}" class="settings tab"><img
                    src="{% static 'images/settings.png' %}">Налаштування</a>

        </div>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button class="exit" onclick=""><img src=" {% static 'images/exit.png' %}">Вихід</button>
        </form>

    </div>
</header>

<main>
    <div class="main-div">
        <div class="menu-friends">
            <a class="menu-urls" id="Friends" href="{% url 'friends' %}">Головна</a>
            <a class="menu-urls" id="Requests" href="{% url 'requests' %}">Запити</a>
            <a class="menu-urls" id="Recomendations" href="{% url 'recomendations' %}">Рекомендації</a>
            <a class="menu-urls" id="AllFriends" href="{% url 'all_friends' %}"><u id="MainText"
                    title="Подчеркнутый текст">Всі друзі</u></a>
        </div>
        <div class="all-menu-friends-div">
            <div class="all-friends">
                <div class="requests-friends-header">
                    <p>Всі друзі</p>
                    <a class="see-all-urls" href="">Дивитись всі</a>
                </div>
                <div class="all-friends-div">
                    {% for friend in friends %}
                    {% if friend.profile2.user.username == user.username %}
                    <div class="friend-profile" href="{% url 'friend_view' friend.id %}">
                        <div class="avatar-nickname-div" id="{{friend.profile1.id}}">
                            {% if friend.profile2.avatar_set.last.image != None %}
                            <img class="avatar-images" src="{{ friend.profile1.avatar_set.last.image.url }}" alt="">
                            {% else %}
                            <img class="avatar-images" src="{% static 'images/standart_user_image.png' %}" alt="">
                            {% endif %}
                            <div class="nickname-name">
                                <p class="nickname-text">{{ friend.profile1.user.first_name }}
                                    {{friend.profile1.user.last_name }}</p>
                                <p>@{{ friend.profile1.user.username }}</p>
                            </div>
                        </div>
                        <div class="buttons-div-recommendations">
                            <button class="add-button" name="add"
                                value="{% url 'request_friend' friend.id %}">Додати</button>
                            <button class="delete-button" name="delete" value="{{friend.profile1.id}}">Видалити</button>
                        </div>
                    </div>
                    {% else %}
                    <div class="friend-profile" href="{% url 'friend_view' friend.id %}">
                        <div class="avatar-nickname-div" id="{{friend.profile2.id}}">
                            {% if friend.profile2.avatar_set.last.image != None %}
                            <img class="avatar-images" src="{{ friend.profile2.avatar_set.last.image.url }}" alt="">
                            {% else %}
                            <img class="avatar-images" src="{% static 'images/standart_user_image.png' %}" alt="">
                            {% endif %}
                            <div class="nickname-name">
                                <p class="nickname-text">{{ friend.profile2.user.first_name }}
                                    {{friend.profile2.user.last_name }}</p>
                                <p>@{{ friend.profile2.user.username }}</p>
                            </div>
                        </div>
                        <div class="buttons-div-recommendations">
                            <button class="add-button" name="add"
                                value="{% url 'request_friend' friend.id %}">Додати</button>
                            <button class="delete-button" name="delete" value="{{friend.profile2.id}}">Видалити</button>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
</main>
{% endblock %}

Messenger/friends/templates/friend_info.html
{% extends "base.html" %}
{% load static %}


{% block title %} Main Page {% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'styles/main.css' %}">
<link rel="stylesheet" href="{% static 'styles/friend_info.css' %}">
<script src="{% static 'js/jquery-3.7.1.min.js' %}" defer></script>
<script src="{% static 'js/friends.js' %}" defer></script>
{% endblock %}

{% block content %}
<header>
    <img src="{% static 'images/logo.png' %}" class="logo">
    <div class="tabsExit">
        <div class="tabs">
            <a href="{% url 'main' %}" class="main tab"><img src="{% static 'images/main.png' %}">Головна</a>

            <a href="{% url 'my_publications' %}" class="publications tab"><img
                    src="{% static 'images/publications.png' %}">Мої публікації</a>

            <a href="{% url 'friends' %}" class="friends tab tab-now"><img
                    src="{% static 'images/friends.png' %}">Друзі</a>

            <a href="{% url 'chats' %}" class="chats tab"><img src="{% static 'images/chat.png' %}">Чати</a>

            <a href="{% url 'settings' user.pk %}" class="settings tab"><img
                    src="{% static 'images/settings.png' %}">Налаштування</a>

        </div>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button class="exit" onclick=""><img src=" {% static 'images/exit.png' %}">Вихід</button>
        </form>

    </div>
</header>


<main>
    <div class="userInfo">
        <div class="miniProfile">
            <div class="avatarNames">
                {% if friend.avatar_set.last.image and friend.avatar_set.last.image.url != None %}
                <img src="{{ friend.avatar_set.last.image.url }}" class="avatar">
                {% endif %}

                <div class="names">
                    <p class="nickname">{{ friend.user.first_name }} {{friend.user.last_name}}</p>
                    <p class="username">@{{ friend.user.username }}</p>
                </div>
            </div>
            <div class="stats">
                <div class="posts">
                    <p class="count">{{ request.user.profile.post_set.all|length }}</p>
                    <p class="name">Дописи</p>
                </div>

                <div class="readers">
                    <p class="count">{{readers}}</p>
                    <p class="name">Читачі</p>
                </div>

                <div class="friends">
                    <p class="count">
                        {{request.user.profile.friendship_sent_request.all.count|add:request.user.profile.friendship_accepted_request.all.count}}
                    </p>
                    <p class="name">Друзі</p>
                </div>
            </div>
        </div>

        <div class="requests">
            <div class="blockName">
                <p class="name"><img src="{% static 'images/friends_gray.png' %}">Запити</p>
                <a href="" class="showAll">Дивитись всі</a>
            </div>
            <div class="users">
                <div class="user">
                    <img src="{% static 'images/avatar2.png' %}">
                    <div class="nameSubscribers">
                        <p class="name">Yehor Aung</p>
                        <p class="subscribers">4.3k Підписників</p>
                    </div>
                </div>

                <div class="user">
                    <img src="{% static 'images/avatar3.png' %}">
                    <div class="nameSubscribers">
                        <p class="name">Ann Ann</p>
                        <p class="subscribers">1.6k Підписників</p>
                    </div>
                </div>

                <div class="user">
                    <img src="{% static 'images/avatar4.png' %}">
                    <div class="nameSubscribers">
                        <p class="name">Yeugen Jenua</p>
                        <p class="subscribers">10.3k Підписників</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="messages">
            <div class="blockName">
                <p class="name"><img src="{% static 'images/messages.png' %}">Повідомлення</p>
                <a href="" class="showAll">Дивитись всі</a>
            </div>
            <div class="users">
                <div class="user mona">
                    <img src="{% static 'images/avatar5.png' %}">
                    <div class="nameSubscribers">
                        <div class="nameTime">
                            <p class="name">Mona Lisa</p>
                            <p class="time">09:41</p>
                        </div>
                        <p class="message">Привіт! Як справи?</p>
                    </div>
                </div>
                <div class="user ann">
                    <img src="{% static 'images/avatar6.png' %}">
                    <div class="nameSubscribers ann">
                        <div class="nameTime">
                            <p class="name">Ann Ti</p>
                            <p class="time">25.04.2025</p>
                        </div>
                        <p class="message">Привіт!</p>
                    </div>
                </div>
                <div class="user">
                    <img src="{% static 'images/avatar7.png' %}">
                    <div class="nameSubscribers">
                        <div class="nameTime">
                            <p class="name">Ness Ty</p>
                            <p class="time">25.04.2025</p>
                        </div>
                        <p class="message">Привіт!</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="PostPostInput">
        {% for post in friend_posts %}
        <div class="post" id="post{{post.id}}" value="{{post.id}}">
            <div class="postHeader">
                <img src="{{post.author.avatar_set.last.image.url}}" class="avatar">
                <p class="text">{{ post.author.user.username }}</p>
                <div class="paintingDiv">
                    {% if user.profile.signature == None %}
                    <img src="{{post.author.signature.url}}" class="painting">
                    {% endif %}
                </div>
            </div>

            <div class="postMain">
                <p class="text">
                    {{ post.title }}<br>
                    {{ post.content }}
                </p>
                <p class="hashtags">
                    {% for tag in post.tags.all %}
                    {{ tag.name }}
                    {% endfor %}
                </p>
                <a href="{{ post.article_link }}" class="publicationLink">{{ post.article_link }}</a>

                <div class="images">
                    {% for img in post.images.all %}
                    <img src="{{ img.file.url }}">
                    {% endfor %}
                </div>
            </div>

            <div class="postFooter">
                <div class="likesViews">
                    <p class="likes like-button {% if profile_now in post.likes.all %}liked{% endif %}"
                        id="{{ post.id }}" value="{% url 'likes' post.pk %}"><img src="{% static 'images/likes.png' %}"
                            class="likesImg" id="like{{post.id}}"><b>{{post.likes.all|length}}</b>
                        Вподобань</p>
                    <p class="likes"><img src="{% static 'images/views.png' %}" class="likesImg">
                        {{post.views.all|length }}
                        Переглядів</p>
                </div>
            </div>
        </div>
        {% endfor %}


        {% endblock %}