Messenger/Messenger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from main.views import MainView
from settings_app.views import UserUpdateView
from chat_app.views import ChatsView
from settings_app.views import save_username
from post_app.views import show_post

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authorization/', include("user_app.urls")),
    path('', MainView.as_view(), name= "main"),
    path("friends/", include("friends.urls")),
    path("publications/", include("post_app.urls")),
    path("settings/<int:pk>/", UserUpdateView.as_view(), name="settings"),
    path("settings/", include("settings_app.urls")),
    path("", include("main.urls")),
    path("chats/", ChatsView.as_view(), name= "chats"),
    path("chats/", include("chat_app.urls")),
    path("save_username/<str:username>/", save_username, name= "save_username"),
    path("show_post/<int:post_pk>/", show_post, name = "show_post")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


Messenger/chat_app/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('chat/<int:group_pk>/', ChatView.as_view(), name='chat'),
    path("create_chat/<int:user_pk>/", create_chat, name = "create_chat"),
    path("delete_group/<int:group_pk>", delete_group, name = "delete_group")
]

Messenger/main/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("add_info", create_name_surname, name = "add_info"),
    path("get_user_readers", get_user_readers, name = "get_user_readers"),
    path("get_user_photo", get_user_photo, name = "get_user_photo"),
    path("get_user_groups", get_user_photo, name = "get_user_groups"),
    path('get_user_requests', get_user_requests, name = "get_user_requests")
]

Messenger/chat_app/models.py
from django.db import models
from django.contrib.auth.models import User
from user_app.models import Profile
# Create your models here.


class ChatGroup(models.Model):
    name = models.CharField(max_length=255)
    members = models.ManyToManyField(Profile, blank=True)
    is_personal_chat = models.BooleanField(default=False) # Чи є цей чат особистим
    admin = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='administered_group')
    avatar = models.ImageField(upload_to='images/group_avatars', blank=True, null=True)

    def __str__(self):
        return f'Група "{self.name}" '
    

class ChatMessage(models.Model):
    content = models.TextField(max_length=4096)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    chat_group = models.ForeignKey(ChatGroup, on_delete=models.CASCADE)
    sent_at = models.DateTimeField(auto_now_add=True)
    attached_image = models.ImageField(upload_to='images/messages', blank=True, null=True)

    def __str__(self):
        return f'Повідомлення від {self.author}. Відправлено {self.sent_at} '

Messenger/user_app/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
import random

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField()
    signature = models.ImageField(upload_to='images/signatures', blank=True, null=True)

    def __str__(self):
        return self.user.username
    

class Avatar(models.Model):
    image = models.ImageField(upload_to='images/avatars')
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    active = models.BooleanField(default=True) # Чи активна ця аватарка (чи використовується вона у профілі)
    shown = models.BooleanField(default=True) # Чи показана ця аватарка в альбомі минулих аватарок

    def __str__(self):
        return f'Аватар для профілю {self.profile}'

        
class Friendship(models.Model):
    profile1 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='friendship_sent_request') # Той, хто надіслав запит на дружбу
    profile2 = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='friendship_accepted_request') # Той, хто має прийняти запит на дружбу
    accepted = models.BooleanField(default=False) # Чи прийнято запит на дружбу

    def __str__(self):
        return f'Дружба між {self.profile1} та {self.profile2}'
    

class VerificationCode(models.Model):
    username = models.CharField(max_length=150)
    code = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    
    @classmethod
    def generate_code(cls):
        return ''.join([str(random.randint(0, 9)) for i in range(6)])
    
    def is_valid(self):
        expiration_time = timezone.timedelta(minutes=30)
        return timezone.now() < self.created_at + expiration_time
    


Messenger/chat_app/forms.py
from django import forms


class MessageForm(forms.Form):
    message= forms.CharField(max_length=255, label="Ваше повідомлення")

Messenger/chat_app/views.py
from django.views.generic import CreateView, TemplateView, FormView
from .models import ChatGroup
from user_app.models import Profile, Friendship
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .forms import MessageForm
from .models import ChatMessage
from post_app.models import Image
import os
from django.conf import settings


class ChatsView(CreateView):
    template_name = "chats.html"
    model = ChatGroup
    fields = ["name", "members", "avatar"]

    def post(self, request, *args, **kwargs):
        print(request.POST.get("formType"))
        print(ChatGroup.objects.filter(name = request.POST.get("group_name")))
        if not ChatGroup.objects.filter(name = request.POST.get("group_name")):
            group = ChatGroup.objects.create(
                name = request.POST.get("group_name"),
                admin = Profile.objects.get(user = request.user)
            )

            list_of_add_users = request.POST.get("choosedUsers").split("_")
            final_list_add = [Profile.objects.get(user = request.user)]

            for user_id in list_of_add_users:
                if user_id != "":
                    print(user_id)
                    final_list_add.append(Profile.objects.get(id = int(user_id)))
            print(final_list_add)

            file = request.FILES.get('avatar_group')
            print(file)

            if file:
                group.avatar = file

            group.members.set(final_list_add)

            group.save()

            print(request.POST)
        return super().post(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user_profile_now = Profile.objects.get(user_id = self.request.user.id)
        final_friends_list = []

        for friend in Friendship.objects.filter(profile2 = user_profile_now, accepted = True):
            final_friends_list.append(friend)
        for friend in Friendship.objects.filter(profile1 = user_profile_now, accepted = True):
            final_friends_list.append(friend)

        user_object = User.objects.get(username = self.request.user)
        print(final_friends_list)
        
        list_personal_chats = ChatGroup.objects.filter(is_personal_chat = True)

        all_not_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = self.request.user), accepted = False)

        context["requests"] = all_not_accepted_get_requests

        context["friends"] = final_friends_list
        
        context["personal_chats"] = list_personal_chats
        
        context["groups"] = ChatGroup.objects.filter(members = Profile.objects.get(user = self.request.user))

        if len(ChatGroup.objects.all()) == 0:
            context["group_id"] =  0
        else:
            context["group_id"] =  ChatGroup.objects.all().last().id + 1

        
        return context
    

    
    def dispatch(self, request, *args, **kwargs):
        try:
            if not request.user.is_authenticated:
                return redirect("register")
        except:
            return redirect("register")
        return super().dispatch(request, *args, **kwargs)
        

def save_group_photo(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            group, created = ChatGroup.objects.get_or_create(admin=Profile.objects.get(user = request.user))
            photo = request.FILES.get('ImageInput') 
            print("\n\n\n", request.FILES)
            print("\n\n\n\n", photo)
            if photo:
                print(2)
                group.avatar = photo
                print("\n\n\n\n", group)
                group.save()
            return redirect('chats')
        


def create_chat(request, user_pk):


    user_to_connect = Profile.objects.get(id=int(user_pk))
    current_user = Profile.objects.get(user = request.user)
    groups_of_user_to_connect = ChatGroup.objects.filter(members=user_to_connect,is_personal_chat=True)
    group_personal_chat = groups_of_user_to_connect.filter(members = current_user).first()
    if not group_personal_chat:
        group_personal_chat = ChatGroup.objects.create(
            name=f'{current_user}-{user_to_connect}',
            is_personal_chat=True,
            admin = current_user,
            avatar = user_to_connect.avatar_set.last().image
        )
        group_personal_chat.members.set([current_user,user_to_connect])
        group_personal_chat.save()
    return redirect(f"chat", group_personal_chat.pk)


class ChatView(FormView):
    '''
    Клас, який відповідає за відображення конкретної чат-групи    
    '''
    template_name = "chat.html"
    form_class = MessageForm

    def dispatch(self, request, *args, **kwargs):
        try:
            if not request.user.is_authenticated:
                return redirect("register")
        except:
            return redirect("register")
        '''
        Метод, який першим приймає запит від веб-сервера, та з'ясовує який це тип запиту. 
        '''
        # Отримуємо об'єкт авторизованого користувача.
        user = Profile.objects.get(user = request.user)
        # Отримуємо pk групи з динамічної url адреси.
        chat_group_pk = self.kwargs['group_pk']
        # Отримуємо об'єкт групи за її pk.
        chat_group = ChatGroup.objects.get(pk=chat_group_pk)
        if user in chat_group.members.all():
            return super().dispatch(request, *args, **kwargs)
        return redirect("chats")
    
    def post(self, request, *args, **kwargs):
        if request.POST.get("formType") == "redact":
        
            group = ChatGroup.objects.get(id = self.kwargs["group_pk"])

            group.name = request.POST.get("group_name")

            list_of_add_users = request.POST.get("choosedUsers").split("_")
            final_list_add = [Profile.objects.get(user = request.user)]

            for user_id in list_of_add_users:
                if user_id != "":
                    print(user_id)
                    final_list_add.append(Profile.objects.get(id = int(user_id)))
            print(final_list_add)

            file = request.FILES.get('avatar_group')
            print(file)


            group.avatar = file

            group.members.set(final_list_add)

            group.save()
        return super().post(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        '''
            Метод для додавання у контекст для класів відображення
        '''

        context = super().get_context_data(**kwargs)
        final_friends_list = []

        user_profile_now = Profile.objects.get(user = self.request.user)

        for friend in Friendship.objects.filter(profile2 = user_profile_now, accepted = True):
            final_friends_list.append(friend)
        for friend in Friendship.objects.filter(profile1 = user_profile_now, accepted = True):
            final_friends_list.append(friend)
        
        group = ChatGroup.objects.get(id = self.kwargs["group_pk"])
        members_count = len(group.members.all())

        chat_group_pk = self.kwargs['group_pk']

        context['group'] = group
        context["groups"] = ChatGroup.objects.filter(members = Profile.objects.get(user = self.request.user))
        context['len_members'] =  members_count
        context['chat_messages'] =  reversed(ChatMessage.objects.filter(chat_group_id = chat_group_pk))
        context["friends"] = final_friends_list
        context["profile_now"] = user_profile_now
        all_not_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = self.request.user), accepted = False)

        context["requests"] = all_not_accepted_get_requests
        user = self.request.user
        all_not_accepted_get_requests = Friendship.objects.filter(profile2 = Profile.objects.get(user = user), accepted = False)

        context["requests"] = all_not_accepted_get_requests
        if ChatGroup.objects.get(id = self.kwargs["group_pk"]).admin == user_profile_now:
            context["is_admin_group"] = True
        else:
            context["is_admin_group"] = False

        list_of_members = ChatGroup.objects.get(id = self.kwargs["group_pk"]).members.all()
        string_of_members = ""
        for member in list_of_members:
            string_of_members += f"{member.id}_"

        context["list_of_members"] = string_of_members

        # повертаємо контекст зі змінами
        return context
    
def delete_group(request, group_pk):
    group = ChatGroup.objects.get(id = group_pk)
    group.delete()
    return redirect("chats")

Messenger/chat_app/templates/chats.html
{% extends "base.html" %}
{% load static %}


{% block title %} Main Page {% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'styles/chats.css' %}">
<script src="{% static 'js/jquery-3.7.1.min.js' %}" defer></script>
<script src="{% static 'js/chat.js' %}" defer></script>
<script src="{% static 'js/all_chats.js' %}" defer></script>
{% endblock %}

{% block content %}
<header>
    <img src="{% static 'images/logo.png' %}" class="logo">
    {% csrf_token %}
    <div class="tabsExit">
        <div class="tabs">
            <a href="{% url 'main' %}" class="main tab"><img src="{% static 'images/main.png' %}">Головна</a>

            <a href="{% url 'my_publications' %}" class="publications tab"><img
                    src="{% static 'images/publications.png' %}">Мої публікації</a>

            <a href="{% url 'friends' %}" class="friends tab">
                <p class="friends-tracker">{{requests|length}}</p><img src="{% static 'images/friends.png' %}">Друзі
            </a>

            <a href="{% url 'chats' %}" class="chats tab tab-now"><img src="{% static 'images/chat.png' %}">Чати</a>

            <a href="{% url 'settings' user.pk %}" class="settings tab"><img
                    src="{% static 'images/settings.png' %}">Налаштування</a>

        </div>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button class="exit" onclick=""><img src=" {% static 'images/exit.png' %}">Вихід</button>
        </form>

    </div>
</header>

<main>
    <div class="contacts-and-create-div">
        <button class="create-chat-btn"><img class="plus-icon" src="{% static 'images/plus.png' %}" alt="">Створити
            груповий чат</button>
        <div class="contacts">
            <div class="contacts-header">
                <img class="contacts-icon" src="{% static 'images/people.png' %}" alt="">
                <p>Контакти</p>
            </div>
            <input class="search" type="text" placeholder="Пошук">
            <div class="all-contacts">
                <select class="hidden">
                    {% for group in personal_chats %}
                    <option value="{{group.id}}"></option>
                    {% endfor %}
                </select>
                {% for friend in friends %}
                {% if friend.profile2 == request.user.profile %}
                <div class="profile" id="{{friend.profile1.id}}">
                    <img class="avatarImage" src="{{friend.profile1.avatar_set.last.image.url}}" alt="">
                    <div class="profile-text-div">
                        <p>{{friend.profile1.user.first_name}} {{friend.profile1.user.last_name}}</p>
                    </div>
                </div>
                {% else %}
                <div class="profile" id="{{friend.profile2.id}}">
                    <img class="avatarImage" src="{{friend.profile2.avatar_set.last.image.url}}" alt="">
                    <div class="profile-text-div">
                        <p>{{friend.profile2.user.first_name}} {{friend.profile2.user.last_name}}</p>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
                <!-- <div class="profile">
                    <img class="avatarImage" src="{% static 'images/avatar14.png' %}" alt="">
                    <div class="profile-text-div">
                        <p>Jane Cooper</p>
                    </div>
                </div>
                <div class="profile">
                    <img class="avatarImage" src="{% static 'images/avatar14.png' %}" alt="">
                    <div class="profile-text-div">
                        <p>Jane Cooper</p>
                    </div>
                </div>
                <div class="profile">
                    <img class="avatarImage" src="{% static 'images/avatar14.png' %}" alt="">
                    <div class="profile-text-div">
                        <p>Jane Cooper</p>
                    </div>
                </div>
                <div class="profile">
                    <img class="avatarImage" src="{% static 'images/avatar14.png' %}" alt="">
                    <div class="profile-text-div">
                        <p>Jane Cooper</p>
                    </div>
                </div>
                <div class="profile">
                    <img class="avatarImage" src="{% static 'images/avatar14.png' %}" alt="">
                    <div class="profile-text-div">
                        <p>Jane Cooper</p>
                    </div>
                </div>
                <div class="profile">
                    <img class="avatarImage" src="{% static 'images/avatar14.png' %}" alt="">
                    <div class="profile-text-div">
                        <p>Jane Cooper</p>
                    </div>
                </div>
                <div class="profile">
                    <img class="avatarImage" src="{% static 'images/avatar14.png' %}" alt="">
                    <div class="profile-text-div">
                        <p>Jane Cooper</p>
                    </div>
                </div>
                <div class="profile">
                    <img class="avatarImage" src="{% static 'images/avatar14.png' %}" alt="">
                    <div class="profile-text-div">
                        <p>Jane Cooper</p>
                    </div>
                </div>
                <div class="profile">
                    <img class="avatarImage" src="{% static 'images/avatar14.png' %}" alt="">
                    <div class="profile-text-div">
                        <p>Jane Cooper</p>
                    </div>
                </div> -->
            </div>
        </div>
    </div>
    <div class="speak-div">
        <div class="start-new-messages">
            <p class="title-of-div">Почніть нове спілкування</p>
            <p class="choose-contact">Оберіть контакт зі списку ліворуч <br>
                або створіть групу, щоб почати спілкування</p>
        </div>
    </div>
    <div class="chat-messages-div">
        <div class="messages">
            <div class="message-header">
                <div class="message-header-text">
                    <img src="{% static 'images/chat2.png' %}" alt="">
                    <p>Повідомлення</p>
                </div>
                <a class="see-all" href="">Дивитись всі</a>
            </div>
            <div class="profiles-all-div">
                {% for group in groups %}
                {% if group.is_personal_chat %}
                <div class="profiles-div">
                    <div class="profles" id="{{group.id}}">
                        {% if group.avatar.url == user.profile.avatar_set.last.image.url %}
                        {% if group.members.last.avatar_set.last.url == user.profile.avatar_set.last.image.url %}
                        {% if group.avatar %}
                        <img class="avatarImage" src="{{group.avatar.url}}" alt="">
                        {% endif %}
                        {% else %}
                        <img class="avatarImage" src="{{group.members.last.avatar_set.last.image.url}}" alt="">
                        {% endif %}
                        {% else %}
                        {% if group.avatar %}
                        <img class="avatarImage" src="{{group.avatar.url}}" alt="">
                        {% endif %}
                        {% endif %}
                        <div class="profiles-text">
                            <div class="header-time-prfl-text">
                                <p>{{group.name}}</p>
                                <p class="time-text datetime">{{group.chatmessage_set.last.sent_at|date:'c'}}</p>
                            </div>
                            <p class="text-content">{{group.chatmessage_set.last.content}}</p>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="group-chats">
            <div class="message-header">
                <div class="message-header-text">
                    <img src="{% static 'images/chat2.png' %}" alt="">
                    <p>Групові чати</p>
                </div>
                <a class="see-all" href="">Дивитись всі</a>
            </div>
            <div class="groups-all-div">

                {% for group in groups %}
                {% if not group.is_personal_chat %}
                <div class="profiles-div">
                    <div class="profles" id="{{group.id}}">
                        <img class="avatarImage" src="{{group.avatar.url}}" alt="">
                        <div class="profiles-text">
                            <div class="header-time-prfl-text">
                                <p>{{group.name}}</p>
                                <p class="time-text datetime">{{group.chatmessage_set.last.sent_at|date:'c'}}</p>
                            </div>
                            <p class="text-content">{{group.chatmessage_set.last.content}}</p>
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="background-blur">

        <form method="post" enctype="multipart/form-data" id="create_group">
            <input type="hidden" class="group_id" value="{{group_id}}">
            <input type="hidden" name="formType" value="create">
            <input type="hidden" class="choosedUsers" name="choosedUsers">
            <div class="group-create">
                {% csrf_token %}
                <input type="hidden" class="postPkInput" name="post_id" value="">
                <button type="button" id="cancel-bg-blur">x</button>
                <p class="NameTitle">Нова група</p>
                <input type="text" placeholder="Пошук" class="input_find" id="">
                <p class="choosed-num">Вибрано: 0</p>
                <div class="list-of-friends">
                    {% for friend in friends %}
                    {% if friend.profile1 == request.user.profile %}
                    <div class="userChoose">
                        <img src="{{friend.profile2.avatar_set.last.image.url}}" class="avatar">
                        <p class="nameLastName">{{friend.profile2.user.first_name}} {{friend.profile2.user.last_name}}
                        </p>
                        <input type="checkbox" class="addedCheckbox" value="{{friend.profile2.pk}}">
                    </div>
                    {% else %}
                    <div class="userChoose">
                        <img src="{{friend.profile1.avatar_set.last.image.url}}" class="avatar">
                        <p class="nameLastName">{{friend.profile1.user.first_name}} {{friend.profile1.user.last_name}}
                        </p>
                        <input type="checkbox" class="addedCheckbox" value="{{friend.profile1.pk}}">
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="btns">
                    <button class="skipBtn btn" type="button">Скасувати</button>
                    <button class="next btn" type="button">Далі</button>
                </div>
            </div>




            <div class="group-create-2-step group-create">
                <input type="hidden" class="postPkInput" name="post_id">
                <button type="button" id="cancel-bg-blur">x</button>
                <p class="NameTitle">Нова група</p>
                <div class="nameInputBlock">
                    <label for="nameInput">
                        <p class="nameLabel">Назва</p>
                    </label>

                    <input type="text" required id="nameInput" placeholder="Введіть назву" class="input_find" id=""
                        name="group_name">
                </div>

                <div class="GroupAvatarChoose">
                    <input type="file" accept="*" class="hidden ImageInput" id="inputAvatarGroup" name="avatar_group">
                    <div class="GroupAvatarDiv">
                        <img src="{% static 'images/newGroup.png' %}" class="GroupAvatar">
                    </div>
                    <div class="divPhoto">
                        <label for="inputAvatarGroup">
                            <div class="AddPhoto">
                                <img src="{% static 'images/add_tag.png' %}" class="small_logo">
                                <p class="AddPhotoText">Додайте фото</p>
                            </div>
                        </label>

                        <label for="inputAvatarGroup">
                            <div class="choosePhoto">
                                <img src="{% static 'images/publications.png' %}" class="small_logo">
                                <p class="AddPhotoText">Оберіть фото</p>
                            </div>
                        </label>
                    </div>
                </div>

                <p class="nameLabel">Учасники</p>
                <div class="group-members">

                </div>

                <div class="btns">
                    <button class="skipBtn skipBtn-2-step btn" type="button">Назад</button>
                    <button class="submit next btn">Створити групи</button>
                </div>
            </div>
        </form>
    </div>
</main>
{% endblock %}